'''Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they have a “cow”.
For every digit the user guessed correctly in the wrong place is a “bull.”
Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.'''

import random

answer = [random.randint(1,9), random.randint(0,9), random.randint(0,9), random.randint(0,9)]

count = 0

def cows_and_bulls():
    cow = 0
    bull = 0
    global count
    count += 1
    guess = input('Please enter your guess (any 4-digit from 1000 to 9999): ')
    guess = [int(i) for i in guess]
    if guess == answer:
        print('You have the correct answer!  You made ' + str(count) + ' guesses!')
    else:
        for i in range(4):
            if guess[i] == answer[i]:
                cow += 1
            elif (guess[i] != answer[i]) & (guess[i] in answer):
                bull += 1
        print(str(cow) + ' cows, ' + str(bull) + 'bulls')
        cows_and_bulls()

cows_and_bulls()

        
